# This compose file defines the services needed to run the indexer-grpc
# It requires a redis instance to be running, and will start the following
# services:
# - indexer-grpc-cache-worker
# - indexer-grpc-file-store (with the local file store on a docker volume)
# - indexer-grpc-data-service
# 
# The indexer-grpc also requires a fullnode to be running with the indexer-grpc
# feature enabled. This connects to your existing movement-full-node.
#
# To start the services, run `docker-compose -p indexer-grpc -f this-file.yml up -d`
version: "3.8"
services:
  redis:
    image: ${REDIS_IMAGE_REPO:-redis}:7.2
    command: redis-server --appendonly yes
    networks:
      - shared
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - 6379:6379
  redis-replica:
    image: ${REDIS_IMAGE_REPO:-redis}:7.2
    command: redis-server --replicaof redis 6379
    networks:
      - shared
    restart: unless-stopped
    expose:
      - 6379
    depends_on:
      - redis
  indexer-grpc-cache-worker:
    image: "us-central1-docker.pkg.dev/citric-plexus-421319/mirage-images/mirage-grpc-worker:v0.0.6"
    networks:
      - shared
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./movement_grpc_sa_key.json
        target: /opt/aptos/movement_grpc_sa_key.json
      - type: volume
        source: indexer-grpc-file-store
        target: /opt/aptos/file-store
      - type: bind
        source: ./cache-worker-config.yaml
        target: /opt/aptos/cache-worker-config.yaml
    command:
      - '/usr/local/bin/aptos-indexer-grpc-cache-worker'
      - '--config-path'
      - '/opt/aptos/cache-worker-config.yaml'
    depends_on:
      - redis
  indexer-grpc-file-store:
    image: "us-central1-docker.pkg.dev/citric-plexus-421319/mirage-images/mirage-grpc-worker:v0.0.6"
    networks:
      - shared
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./movement_grpc_sa_key.json
        target: /opt/aptos/movement_grpc_sa_key.json
      - type: volume
        source: indexer-grpc-file-store
        target: /opt/aptos/file-store
      - type: bind
        source: ./file-store-config.yaml
        target: /opt/aptos/file-store-config.yaml
    command:
      - '/usr/local/bin/aptos-indexer-grpc-file-store'
      - '--config-path'
      - '/opt/aptos/file-store-config.yaml'
    depends_on:
      - redis
  indexer-grpc-data-service:
    image: "us-central1-docker.pkg.dev/citric-plexus-421319/mirage-images/mirage-grpc-worker:v0.0.6"
    networks:
      - shared
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./movement_grpc_sa_key.json
        target: /opt/aptos/movement_grpc_sa_key.json
      - type: volume
        source: indexer-grpc-file-store
        target: /opt/aptos/file-store
      - type: bind
        source: ./data-service-config.yaml
        target: /opt/aptos/data-service-config.yaml
      - type: bind
        source: ./data-service-grpc-server.key
        target: /opt/aptos/certs/data-service-grpc-server.key
      - type: bind
        source: ./data-service-grpc-server.crt
        target: /opt/aptos/certs/data-service-grpc-server.crt
    command:
      - '/usr/local/bin/aptos-indexer-grpc-data-service'
      - '--config-path'
      - '/opt/aptos/data-service-config.yaml'
    ports:
      - "50052:50052" # GRPC non-secure
      - "50053:50053" # GRPC secure
      - "18084:8084" # health
    depends_on:
      - indexer-grpc-cache-worker
      - indexer-grpc-file-store
      - redis-replica

# This connects to your existing movement-full-node network
networks:
  shared:
    external: true
    name: "movement-full-node_default"

volumes:
  indexer-grpc-file-store:
    name: indexer-grpc-file-store