health_check_port: 8083
server_config:
  redis_main_instance_address: redis://redis:6379
  file_store_config:
    file_store_type: GcsFileStore
    gcs_file_store_bucket_name: mirage-stream-cache-bucket-movement
  chain_id: 126